name: Build

on: [push]

jobs:
 build:
   runs-on: ubuntu-22.04
   strategy:
     fail-fast: false
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.7'

     - name: Install dependencies
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt update \
         sudo apt install -y repo git mka lunch tar

   - name: mkdir and cd
     run: mkdir lineage-19.1 && cd lineage-19.1
   - name: repo init
     run: repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 --git-lfs

   - name: git clone
     run: git clone https://github.com/K9100ii/s5neolte-manifest.git -b lineage-19.1 .repo/local_manifests

   - name: repo sync
     run: repo sync --force-sync --no-tags --no-clone-bundle -c
   - name: build
     run: |
       . build/envsetup.sh \
       lunch lineage_s5neolte-userdebug \
       mka otapackage

   - name: tar
     run: |
       mkdir -p geili && tar -cf geili/file.tar lineage-19.1

   - name: upload geili Zip
      uses: actions/upload-artifact@v2
      with:
        name: tolli geili
         path: geili/*
         if-no-files-found: error
