name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          sudo apt update 
          sudo apt install -y repo git mkalias python3 python3-pip tar
          pip3 installiert lunch

      - name: Setup and build
        run: |
          mkdir lineage-19.1
          cd lineage-19.1
          repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 --git-lfs
          git clone https://github.com/K9100ii/s5neolte-manifest.git -b lineage-19.1 .repo/local_manifests
          repo sync --force-sync --no-tags --no-clone-bundle -c
          . build/envsetup.sh 
          lunch lineage_s5neolte-userdebug 
          mka otapackage
          
      - name: Create tar archive
        run: |
          mkdir -p geili
          tar -cf geili/file.tar lineage-19.1

      - name: Upload geili Zip
        uses: actions/upload-artifact@v2
        with:
          name: tolli geili
          path: geili/*
          if-no-files-found: error
